import type { ContentSummary, DeliveryImage } from '@autoedit/astro-cms';
import { cms } from '../lib/cms';

export type Tone = 'lime' | 'orange' | 'blue' | 'ink';

export type Article = {
  id: string;
  href: string;
  title: string;
  excerpt: string;
  category: string;
  categoryHref?: string;
  author: string;
  date: string; // ISO
  readingTime: number;
  tone: Tone;
  // Cover generated by the CMS (headline figure + chart), also the social image.
  cover?: DeliveryImage;
};

export const AUTHOR = 'Hopone Newsroom';

export const categories = [
  { name: 'Markets', desc: 'Stocks, valuations and earnings from the big running brands.' },
  { name: 'Brands', desc: 'Strategy, product launches and the battle for market share.' },
  { name: 'Races', desc: 'The economics of marathons, trail races and mass-participation events.' },
  { name: 'Sponsorship', desc: 'Athlete contracts, title sponsors and media rights.' },
  { name: 'Startups', desc: 'Funding rounds, apps, wearables and new entrants.' },
  { name: 'Retail', desc: 'Distribution, DTC, specialty run shops and e-commerce.' },
];

export const categorySlug = (name: string) => name.toLowerCase();

// Each brief restates a figure from a sourced article.
export const briefs = [
  'Nike Q1 revenue falls 4% to $11.2bn; Greater China down 22%',
  '166,000 runners enter the first Paris Marathon ballot',
  'Dublin Marathon entry rises 18% to €130 for 2027',
  'Generali replaces BMW as Berlin Marathon title sponsor after 16 years',
  'Copenhagen Half: 188,522 entries for 45,000 places',
  'Grandma’s Marathon 2027 sells out in 174 minutes',
  'Decathlon negotiates a 50% stake in Sport 2000’s central buying company',
  'Brooklyn run club Peak and Pace made $640,000 in 2025',
];

const TONES: Tone[] = ['lime', 'orange', 'blue', 'ink'];

/** Stable colour per article, for cards without a cover. */
const toneOf = (id: string) => TONES[[...id].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 0) % TONES.length]!;

export const toArticle = (c: ContentSummary): Article => ({
  id: c.id,
  href: c.path,
  title: c.title,
  excerpt: c.excerpt,
  category: c.category?.name ?? 'News',
  categoryHref: c.category?.path,
  author: c.persona?.name ?? AUTHOR,
  date: (c.publishedAt ?? c.updatedAt).slice(0, 10),
  readingTime: c.readingMinutes || 1,
  tone: toneOf(c.id),
  cover: c.hero ?? undefined,
});

/** Latest published articles, newest first. */
export async function getArticles(count = 13): Promise<Article[]> {
  const { items } = await cms.contents({ pageSize: count });
  return items.map(toArticle);
}

export const formatDate = (iso: string | Date) =>
  new Intl.DateTimeFormat('en-US', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(iso));
